# Generated by Django 6.0.5 on 2026-05-27 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_id', models.CharField(blank=True, max_length=255)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 - Direct (fuel combustion)'), ('SCOPE_2', 'Scope 2 - Indirect (purchased electricity)'), ('SCOPE_3', 'Scope 3 - Value chain (travel, procurement)')], max_length=10)),
                ('category', models.CharField(choices=[('FUEL_STATIONARY', 'Stationary Combustion (generators, boilers)'), ('FUEL_MOBILE', 'Mobile Combustion (company vehicles)'), ('ELECTRICITY', 'Purchased Electricity'), ('BUSINESS_TRAVEL_AIR', 'Business Travel - Flights'), ('BUSINESS_TRAVEL_HOTEL', 'Business Travel - Hotels'), ('BUSINESS_TRAVEL_GROUND', 'Business Travel - Ground Transport'), ('PROCUREMENT', 'Procurement / Purchased Goods')], max_length=40)),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('raw_unit', models.CharField(max_length=50)),
                ('raw_data', models.JSONField()),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('normalized_unit', models.CharField(default='kg_co2e', max_length=20)),
                ('emission_factor_used', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged - Needs Attention'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=10)),
                ('flag_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.dataingestion')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
